spring:
  application:
    name: cp-portal-ui
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  freemarker:
    template-loader-path: classpath:/templates/
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CP_CLIENT_ID}
            client-secret: ${KEYCLOAK_CP_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${CP_PORTAL_UI_URI}/login/oauth2/code/keycloak
            scope:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}

keycloak:
  superAdminRole: cp-cluster-admin-role
  oauth2LoginPath: /oauth2/authorization/keycloak
  logoutUri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/logout
  introspectUri: ${KEYCLOAK_URI}/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/token/introspect

server:
  port: ${PORT:8090}
  servlet:
    session:
      cookie:
        name: CPADMINPORTALSESSION

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health

private:
  repository:
    url: ${REPOSITORY_URL}

guide:
  url: https://github.com/K-PaaS/container-platform/tree/master/use-guide/portal/
  url-eng: https://github.com/K-PaaS/cp-guide-eng/tree/master/use-guide/portal/
  url-playpark: https://github.com/K-PaaS/container-platform/blob/playpark/use-guide/portal/container-platform-portal-deploy-guide.md#
  name: cp-portal-use-guide-{}.md

catalog:
  default:
    repo:
      url: ${CHART_REPO_URL}
      name: ${CHART_REPO_NAME}
      username: ${CHART_REPO_USERNAME}
      password: ${CHART_REPO_PASSWORD}
      cert: ${CHART_REPO_CRT} # base64 encoded certificate

logging:
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: local

logging:
  file:
    path: logs

cpApi:
  url: http://localhost:3333
chaosApi:
  url: http://localhost:8092
catalogApi:
  url: http://localhost:8093

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  file:
    path: /home/1000/logs

cpApi:
  url: ${CP_PORTAL_API_URI}
chaosApi:
  url: ${CP_PORTAL_CHAOS_API_URI}
catalogApi:
  url: ${CP_PORTAL_CATALOG_API_URI}